// app/src/lib/components/AvatarMenu.svelte
<script lang="ts">
  import authClient from '$lib/auth-client'
  import { resolve } from '$app/paths'
  import { goto } from '$app/navigation'
  import type { User } from '$lib/server/auth'
  
  const { user }: { user: User } = $props()

  async function handleLogout() {
    await authClient.signOut({
      fetchOptions: {
        onSuccess: async () => {
          await goto(resolve('/'))
        }
      }
    })
  }
</script>

{#if user.isAdmin}
  <span class="admin-badge">admin</span>
{/if}
<div class="avatar-menu">
  <button class="avatar-btn">
    {#if user.image}
      <img src={user.image} alt={user.name} />
    {:else}
      <span class="avatar-placeholder">{user.name[0].toUpperCase()}</span>
    {/if}
  </button>
  <div class="avatar-dropdown">
    <div class="avatar-dropdown-user">{user.name}</div>
    {#if user.isAdmin}
      <a href={resolve('/admin')}>Admin interface</a>
    {/if}
    <button onclick={handleLogout}>Sign out</button>
  </div>
</div>

// app/src/component/AvatarMenu.tsx
'use client'

import authClient from '@/lib/auth-client'
import { ConfigCtx } from '@/lib/contexts'
import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { useContext } from 'react'

export default function AvatarMenu() {
  const session = authClient.useSession()
  const cfg = useContext(ConfigCtx)
  const router = useRouter()

  if (!session.data) {
    if (cfg.isSetupComplete && cfg.hasGithubAuth)
      return (
        <button className='nav-link' onClick={() => authClient.signIn.social({ provider: 'github' })}>
          Sign in via GitHub
        </button>
      )
    else return <></>
  } else {
    const user = session.data.user
    return (
      <>
        {user.isAdmin && <span className='admin-badge'>admin</span>}
        <div className='avatar-menu'>
          <button className='avatar-btn'>
            {user.image ? (
              <Image src={user.image} alt={user.name} width={28} height={28} loading='eager' />
            ) : (
              <span className='avatar-placeholder'>{user.name[0].toUpperCase()}</span>
            )}
          </button>
          <div className='avatar-dropdown'>
            <div className='avatar-dropdown-user'>{user.name}</div>
            {/* TODO admin route {user.isAdmin && <Link href='/admin'>Admin interface</Link>} */}
            <button
              onClick={() => {
                authClient.signOut({
                  fetchOptions: {
                    onSuccess: () => {
                      router.push('/')
                    },
                  },
                })
              }}
            >
              Sign out
            </button>
          </div>
        </div>
      </>
    )
  }
}
