// app/src/routes/setup/+page.svelte
<script lang="ts">
  import { resolve } from '$app/paths'

  interface SetupStatus {
    githubConfigSaved: boolean
    seeded: boolean
    seeding: boolean
  }

  let githubConfigSaved = $state(false)
  let seeding = $state(false)
  let seeded = $state(false)
  let configError = $state('')
  let seedError = $state('')
  let savingConfig = $state(false)

  let clientId = $state('')
  let clientSecret = $state('')

  // Progress state
  let showProgress = $state(false)
  let showLog = $state(false)
  let progressPercent = $state(0)
  let progressText = $state('Starting...')
  let logLines = $state<string[]>([])
  let logArea: HTMLDivElement | undefined = $state()

  // Check initial status on mount
  $effect(() => {
    fetch('/api/setup/status')
      .then(r => r.json() as Promise<SetupStatus>)
      .then(data => {
        githubConfigSaved = data.githubConfigSaved
        seeded = data.seeded
        if (data.seeding) {
          seeding = true
          showProgress = true
          showLog = true
          streamLogs()
        }
      })
      .catch(() => {})
  })

  function saveConfig() {
    if (!clientId.trim() || !clientSecret.trim()) {
      configError = 'Client ID and Client Secret are required.'
      return
    }
    savingConfig = true
    configError = ''

    fetch('/api/setup/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        githubClientId: clientId.trim(),
        githubClientSecret: clientSecret.trim(),
      }),
    })
      .then(r => {
        if (!r.ok) throw new Error('Failed to save configuration')
        githubConfigSaved = true
      })
      .catch((err: Error) => {
        configError = err.message
      })
      .finally(() => {
        savingConfig = false
      })
  }

  function startSetup() {
    seeding = true
    showProgress = true
    showLog = true
    seedError = ''

    fetch('/api/setup/seed', { method: 'POST' })
      .then(r => {
        if (!r.ok) throw new Error('Failed to start setup')
        streamLogs()
      })
      .catch((err: Error) => showSeedError(err.message))
  }

  function streamLogs() {
    const source = new EventSource('/api/setup/stream')

    source.onmessage = event => {
      const data = JSON.parse(event.data as string) as {
        type: string
        step?: number
        total?: number
        label?: string
        line?: string
        message?: string
      }
      if (data.type === 'progress') {
        progressPercent = Math.round(((data.step ?? 0) / (data.total ?? 1)) * 100)
        progressText = `${data.label} (${data.step}/${data.total})`
      } else if (data.type === 'log') {
        logLines = [...logLines, data.line ?? '']
        // Auto-scroll
        requestAnimationFrame(() => {
          if (logArea) {
            const atBottom = logArea.scrollHeight - logArea.scrollTop - logArea.clientHeight < 20
            if (atBottom) logArea.scrollTop = logArea.scrollHeight
          }
        })
      } else if (data.type === 'done') {
        source.close()
        progressPercent = 100
        seeded = true
        seeding = false
      } else if (data.type === 'error') {
        source.close()
        showSeedError(data.message ?? 'Unknown error')
      }
    }

    source.onerror = () => {
      source.close()
      fetch('/api/setup/status')
        .then(r => r.json() as Promise<SetupStatus>)
        .then(data => {
          if (data.seeded) {
            seeded = true
            seeding = false
          } else if (!data.seeding) {
            showSeedError('Connection lost')
          }
        })
        .catch(() => {})
    }
  }

  function showSeedError(msg: string) {
    seedError = msg
    seeding = false
    showProgress = false
  }
</script>

<svelte:head>
  <title>Lean Workbench Setup</title>
</svelte:head>

<main style="max-width: 600px;">
  <h1>Setup</h1>

  <h2>Step 1: GitHub Authentication</h2>
  <p style="color: #607D8B; font-size: 13px;">
    Create a
    <a href="https://github.com/settings/developers" target="_blank">GitHub OAuth App</a>
    and enter the credentials below.
  </p>

  {#if !githubConfigSaved}
    <div class="form-field">
      <label for="client-id">Client ID</label>
      <input id="client-id" type="text" bind:value={clientId} placeholder="Ov23li..." disabled={savingConfig} />
    </div>
    <div class="form-field">
      <label for="client-secret">Client Secret</label>
      <input
        id="client-secret"
        type="password"
        bind:value={clientSecret}
        placeholder="Enter client secret"
        disabled={savingConfig}
      />
    </div>
    {#if configError}
      <div class="setup-error">{configError}</div>
    {/if}
    <button class="primary" onclick={saveConfig} disabled={savingConfig}>
      {savingConfig ? 'Saving...' : 'Save Configuration'}
    </button>
  {:else}
    <div class="setup-success">Authentication configured.</div>
  {/if}

  <hr class="section-divider" />

  <h2>Step 2: Initialize Data Volume</h2>
  <p style="color: #607D8B; font-size: 13px;">
    Install elan, download pre-compiled Mathlib, and set up project templates. This may take several minutes.
  </p>

  {#if seeded}
    <div class="setup-success">
      Setup complete! <a href={resolve('/')}>Continue to Lean Workbench</a>
    </div>
  {:else}
    <button class="primary" onclick={startSetup} disabled={!githubConfigSaved || seeding}>
      {#if seeding}
        Setting up...
      {:else if seedError}
        Retry Setup
      {:else}
        Start Setup
      {/if}
    </button>

    {#if showProgress}
      <div class="progress-area">
        <div class="progress-bar-outer">
          <div class="progress-bar-inner" style="width: {progressPercent}%;"></div>
        </div>
        <div class="progress-label">
          <span class="spinner"></span>
          <span>{progressText}</span>
        </div>
      </div>
    {/if}

    {#if showLog && logLines.length > 0}
      <div class="log-area" bind:this={logArea}>
        {#each logLines as line, i (i)}
          {line + '\n'}
        {/each}
      </div>
    {/if}

    {#if seedError}
      <div class="setup-error">Setup failed: {seedError}</div>
    {/if}
  {/if}
</main>

<style>
  .form-field {
    margin-bottom: 12px;
  }
  .form-field label {
    display: block;
    font-size: 13px;
    font-weight: 600;
    margin-bottom: 4px;
  }
  .form-field input {
    width: 100%;
    padding: 8px 10px;
    font-size: 14px;
    border: 1px solid #d1d9e2;
    border-radius: 0.5rem;
    font-family: inherit;
    box-sizing: border-box;
  }
  .form-field input:disabled {
    background: #f5f5f5;
    color: #999;
  }
  .section-divider {
    border: none;
    border-top: 1px solid #e4ebf3;
    margin: 24px 0;
  }
  .progress-area {
    margin: 20px 0;
  }
  .progress-bar-outer {
    width: 100%;
    height: 8px;
    background: #e4ebf3;
    border-radius: 4px;
    overflow: hidden;
  }
  .progress-bar-inner {
    height: 100%;
    width: 0%;
    background: #386ee0;
    border-radius: 4px;
    transition: width 0.4s ease;
  }
  .progress-label {
    margin-top: 8px;
    font-size: 13px;
    color: #607d8b;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .spinner {
    display: inline-block;
    width: 12px;
    height: 12px;
    border: 2px solid #d1d9e2;
    border-top-color: #386ee0;
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
    flex-shrink: 0;
  }
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
  .log-area {
    margin: 12px 0;
    padding: 12px;
    background: #1a1a2e;
    color: #a0d0a0;
    border-radius: 0.5rem;
    font-family: 'Courier New', monospace;
    font-size: 12px;
    line-height: 1.5;
    max-height: 300px;
    overflow-y: auto;
    white-space: pre-wrap;
    word-break: break-all;
  }
  .setup-success {
    margin: 20px 0;
    padding: 12px 16px;
    background: #f0fdf4;
    border: 1px solid #86efac;
    border-radius: 0.5rem;
    color: #166534;
    font-weight: 500;
  }
  .setup-success a {
    color: #386ee0;
    text-decoration: none;
    font-weight: 600;
  }
  .setup-success a:hover {
    text-decoration: underline;
  }
  .setup-error {
    margin: 12px 0;
    padding: 12px 16px;
    background: #fef2f2;
    border: 1px solid #fca5a5;
    border-radius: 0.5rem;
    color: #dc2626;
    font-weight: 500;
  }
</style>

// src/app/setup/page.tsx
'use client'

import Link from 'next/link'
import { redirect } from 'next/navigation'
import { useContext, useEffect, useRef, useState } from 'react'
import useSWR from 'swr'

import { useServerAction } from '@/lib/client/util'
import { ConfigCtx } from '@/lib/contexts'
import { LEAN_VERSION_RE } from '@/lib/util'

import { fetchSetupStatus, saveSetupConfig, startSeed } from './actions'

type Phase = 'config' | 'seeding' | 'done' | 'error'

/** Fetch mathlib4 v4.* tags, newest-first, paginating until exhausted. */
async function fetchLeanVersions(): Promise<string[]> {
  const versions: string[] = []
  // This relies on version tags being returned first.
  const res: Response = await fetch('https://api.github.com/repos/leanprover-community/mathlib4/tags?per_page=100')
  if (!res.ok) throw new Error(`GitHub API ${res.status}`)
  const data = (await res.json()) as { name: string }[]
  for (const item of data) if (LEAN_VERSION_RE.test(item.name)) versions.push(item.name)
  return versions
}

export default function Setup() {
  const cfg = useContext(ConfigCtx)
  const [wasCompleteOnMount] = useState(cfg.isSetupComplete)
  // Redirect to index on new visits, but keep the page open during actual setup
  if (wasCompleteOnMount) redirect('/')

  const [configSaved, setConfigSaved] = useState(false)
  const [phase, setPhase] = useState<Phase>('config')
  const [seedError, setSeedError] = useState('')
  const [progress, setProgress] = useState({ pct: 0, label: '' })
  const [logs, setLogs] = useState<string[]>([])
  const [leanVersion, setLeanVersion] = useState<string | undefined>()
  const { data: leanVersions } = useSWR('leanVersions', fetchLeanVersions)
  const logRef = useRef<HTMLDivElement>(null)

  const [configError, saveConfigAction, savingConfig] = useServerAction(
    (formData: FormData) => saveSetupConfig(formData),
    () => setConfigSaved(true),
  )

  // Sync with server state on mount (handles page reload during seeding).
  useEffect(() => {
    fetchSetupStatus().then(status => {
      if (status.configSaved) setConfigSaved(true)
      if (status.seeded) setPhase('done')
      else if (status.seeding) setPhase('seeding')
    })
  }, [])

  // Auto-scroll log area.
  useEffect(() => {
    const el = logRef.current
    if (!el) return
    el.scrollTop = el.scrollHeight
  }, [logs])

  // Stream seed events whenever we're in the seeding phase.
  useEffect(() => {
    if (phase !== 'seeding') return
    const source = new EventSource('/api/setup-events')
    source.onmessage = event => {
      const data = JSON.parse(event.data)
      if (data.type === 'progress') {
        const pct = Math.round((data.step / data.total) * 100)
        setProgress({ pct, label: `${data.label} (${data.step}/${data.total})` })
      } else if (data.type === 'log') {
        setLogs(prev => [...prev, data.line])
      } else if (data.type === 'done') {
        source.close()
        setProgress({ pct: 100, label: '' })
        setPhase('done')
      } else if (data.type === 'error') {
        source.close()
        setSeedError(data.message)
        setPhase('error')
      }
    }
    source.onerror = () => {
      source.close()
      fetchSetupStatus().then(status => {
        if (status.seeded) {
          setProgress({ pct: 100, label: '' })
          setPhase('done')
        } else if (!status.seeding) {
          setSeedError('Connection lost')
          setPhase('error')
        }
      })
    }
    return () => source.close()
  }, [phase])

  const [origin, setOrigin] = useState('')
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setOrigin(window.location.origin)
  }, [])

  async function handleStartSeed() {
    setSeedError('')
    setLogs([])
    setProgress({ pct: 0, label: 'Starting...' })
    setPhase('seeding')
    const result = await startSeed(leanVersion)
    if ('error' in result) {
      setSeedError(result.error)
      setPhase('error')
    }
  }

  return (
    <>
      <h1>Setup</h1>
      <h2>Step 1: Configuration</h2>
      {configSaved ? (
        <div className='setup-done-msg'>Configuration saved.</div>
      ) : (
        <form action={saveConfigAction} className='setup-form'>
          <h3>Domain configuration</h3>
          <p style={{ color: '#607D8B', fontSize: '13px' }}>
            Provide the URL on which you will host the Lean Workbench, for example <code>https://myserver.com</code>.
          </p>
          <div className='setup-field'>
            <input
              type='url'
              id='baseUrl'
              name='baseUrl'
              value={origin}
              onChange={e => setOrigin(e.target.value)}
              required
            />
          </div>
          <h3>GitHub Authentication</h3>
          <p style={{ color: '#607D8B', fontSize: '13px' }}>
            Create a{' '}
            <a href='https://github.com/settings/developers' target='_blank' rel='noreferrer'>
              GitHub OAuth App
            </a>
            . When prompted, set the &quot;Authorization callback URL&quot; to
          </p>
          <code>{origin && `${origin}/api/auth/callback/github`}</code>
          <p style={{ color: '#607D8B', fontSize: '13px' }}>
            Then enter the client ID and secret of your OAuth App here.
          </p>
          <div className='setup-field'>
            <label htmlFor='clientId'>Client ID</label>
            <input type='text' id='clientId' name='clientId' placeholder='Ov23li...' required />
          </div>
          <div className='setup-field'>
            <label htmlFor='clientSecret'>Client Secret</label>
            <input
              type='password'
              id='clientSecret'
              name='clientSecret'
              placeholder='Enter client secret'
              autoComplete='off'
              required
            />
          </div>
          <button type='submit' className='primary' disabled={savingConfig}>
            {savingConfig ? 'Saving...' : 'Save Configuration'}
          </button>
        </form>
      )}

      {configError && <div className='setup-error-msg'>{configError}</div>}

      <hr className='setup-divider' />

      <h2>Step 2: Initialize Data Volume</h2>
      <p style={{ color: '#607D8B', fontSize: '13px' }}>
        Install elan, download pre-compiled Mathlib, and set up project templates. This may take several minutes.
      </p>

      {phase === 'done' ? (
        <div className='setup-done-msg'>
          Setup complete! <Link href='/'>Continue to Lean Workbench</Link>
        </div>
      ) : (
        <>
          {phase !== 'seeding' && (
            <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
              <button className='primary' disabled={!configSaved} onClick={handleStartSeed}>
                {phase === 'error' ? 'Retry Setup' : 'Start Setup'}
              </button>
              with Lean version:
              <select
                value={leanVersion ?? ''}
                onChange={e => setLeanVersion(e.target.value || undefined)}
                disabled={!leanVersions}
              >
                <option>{leanVersions ? 'Latest' : 'Loading…'}</option>
                {leanVersions?.map(v => (
                  <option key={v} value={v}>
                    {v}
                  </option>
                ))}
              </select>
            </div>
          )}

          {(phase === 'seeding' || phase === 'error') && progress.pct > 0 && (
            <div className='setup-progress'>
              <div className='setup-progress-outer'>
                <div className='setup-progress-inner' style={{ width: `${progress.pct}%` }} />
              </div>
              {(phase === 'seeding' || phase === 'error') && (
                <div className='setup-progress-label'>
                  {phase === 'seeding' && <span className='setup-spinner' />}
                  <span>{progress.label || 'Starting...'}</span>
                </div>
              )}
            </div>
          )}

          {(phase === 'seeding' || phase === 'error') && logs.length > 0 && (
            <div className='setup-log' ref={logRef}>
              {logs.map((line, i) => (
                <div key={i}>{line}</div>
              ))}
            </div>
          )}

          {seedError && <div className='setup-error-msg'>Setup failed: {seedError}</div>}
        </>
      )}
    </>
  )
}
